#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         20
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Cargamos el fonde de pantalla
feh --bg-max /home/alexc/Imágenes/wallpaper/fondo.jpg &

# Launch theme polybar sky-blue
# ~/.config/polybar/forest /launch.sh &

zsh ~/.config/polybar/launch.sh --forest

# Seguimiento con el raton para ver el focus de la ventana
bspc config focus_follows_pointer true

picom --experimental-backends &
bspc config border_width 1

#Arreglar el mouse
xsetroot -cursor_name left_ptr &

# Setear brillo de pantalla
#xrandr --output eDP --brightness 0.86
